version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    networks:
      - mynetwork

networks:
  mynetwork:
